import type { Metadata } from 'next';
import './globals.css';
import NavBar from './(components)/Navbar';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body>
				<NavBar></NavBar>
				<main className="container mx-auto p-5">{children}</main>
			</body>
		</html>
	);
}
